name: 10-External
on:
  workflow_dispatch 

jobs:
  external-job:
    runs-on: windows-latest
    steps:
      - name: Call external workflow
        uses: ./.github/workflows/10a-External-Script.yml
        with:
          name: "External Workflow" 
      - name: Final step
        run: |
          echo "This is the final step of the external job."