name: 3-Variables
on: workflow_dispatch

# varaibles: Use env or repository defined variable (repo home -> settings -> secrets and variables)
env:
  a: 3
  b: 4

jobs:
  job-variables:
    runs-on: windows-latest
    steps:
      - name: add
        run: |
          set /a sum=${{env.a}}+${{env.b}}
          echo 'The sum of $a and $b is %sum%'
