name: 4-VariableGroups
on: workflow_dispatch

# Not literally available but something similar
# variables: Use env or repository defined variable (repo home -> settings -> secrets and variables)
jobs: 
  example-groups:
    runs-on: windows-latest
    steps:
    - name: Groups and Variables
      run: |
        echo My name is ${{vars.First}} ${{vars.Last}}
        echo My secret is ${{secrets.Secret}}
        
