name: 8-Stategies
on: workflow_dispatch

jobs:
  requirements:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [ '8.0', '9.0', '10.0' ] 
    runs-on: ${{ matrix.os }}
    steps:
      - name: OS and .NET version
        run: |
          echo "Using .NET version ${{ matrix.dotnet }} on ${{ matrix.os }}"
          
        
